server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git # used when config is stored in git repo
  #    active: native # used only when using classpath or file system locations approaches
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          #        native:
          #          search-locations: "classpath:/config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
